// Everything the hub manager app says, in English and Hindi. The language is
// the one chosen with the EN / हिं switch (shared with the driver app's setting;
// Kannada falls back to English here).

import { useI18n } from "@/src/i18n";

const REASONS_EN: Record<string, string> = {
  unwell: "Unwell", family_emergency: "Family emergency", vehicle_problem: "Vehicle problem",
  transport_problem: "Transport problem", personal: "Personal", other: "Other",
};
const REASONS_HI: Record<string, string> = {
  unwell: "तबीयत खराब", family_emergency: "पारिवारिक आपात स्थिति", vehicle_problem: "गाड़ी में समस्या",
  transport_problem: "आने-जाने में समस्या", personal: "निजी कारण", other: "अन्य",
};

const en = {
  // sign in
  app_name: "Ride91 Hub",
  signin_title: "Sign in",
  signin_sub: "Use your hub manager login",
  username: "Username",
  password: "Password",
  signin: "Sign in",
  signin_bad: "Wrong username or password.",
  signin_locked: "Too many tries. Wait 15 minutes and try again.",
  signin_fail: "Could not sign in. Check your network.",
  pick_hub: "Which hub?",
  pick_hub_sub: "Your account covers every hub. Choose one to open.",
  sign_out: "Sign out",
  change_hub: "Change hub",
  // tabs
  tab_today: "Today",
  tab_drivers: "Drivers",
  tab_money: "Money",
  tab_inbox: "Inbox",
  // general
  call: "Call",
  message: "Message",
  cancel: "Cancel",
  save: "Save",
  loading: "Loading…",
  offline: "No connection. Showing the last update.",
  none: "—",
  // today
  on_duty_now: "On duty now",
  coming: "Coming",
  not_coming: "Not coming",
  no_answer: "No answer",
  needs_you: "Needs you now",
  all_clear: "Nothing needs you right now.",
  cash_to_collect: "Cash to collect",
  withdrawals: "Withdrawals",
  requests: "Requests",
  messages: "Messages",
  no_shift_times: (n: number) => `${n} driver${n === 1 ? " has" : "s have"} no shift time, so no alarm rings for them. Set it on the driver's page.`,
  att: {
    not_coming: "Not coming",
    not_started: "Has not started duty",
    no_answer: "Did not answer the alarm",
    late: "Said coming, not started",
    tracking_stopped: "Tracking stopped",
    over_cash_limit: "Cash over the limit",
  } as Record<string, string>,
  att_location_off: "Location is off on the phone",
  att_no_signal: "No position for over 10 minutes",
  back_by: (d: string) => `back by ${d}`,
  shift_at: (t: string) => `shift ${t}`,
  // drivers
  search: "Search name or phone",
  no_drivers: "No drivers in this hub.",
  status: {
    no_shift_time: "No shift time", alarm_pending: "Alarm not rung", ringing: "Alarm ringing", no_answer: "No answer",
    coming: "Coming", not_coming: "Not coming", late: "Late", not_started: "Not started", started: "On duty",
  } as Record<string, string>,
  on_duty: "On duty",
  off_duty: "Off duty",
  not_online: "Not online on any app",
  charging: "Charging",
  to_charger: "Going to charger",
  on_duty_for: (d: string) => `On duty ${d}`,
  owes: (amt: string) => `Owes ${amt}`,
  over_limit: "over limit",
  // driver page
  shift_time: "Shift time",
  shift_time_hint: "24-hour time, like 07:00. The alarm rings one hour before.",
  shift_saved: "Shift time saved.",
  shift_bad: "Enter the time as HH:MM, like 07:00.",
  car: "Car",
  no_car: "No car assigned",
  cash_owed: "Cash owed",
  cash_received: "Cash received",
  working: "Working",
  recent_taps: "Today's activity",
  no_taps: "No button presses yet today.",
  open_map: "Map",
  conversation: "Messages",
  no_messages: "No messages yet.",
  type_message: "Write a message…",
  send: "Send",
  automatic: "automatic",
  taps: {
    start_duty: "Started duty", end_duty: "Ended duty", to_charger: "Going to charger",
    charging_started: "Charging started", charging_finished: "Charging finished",
  } as Record<string, string>,
  tap_on: (app: string) => `${app} on`,
  tap_off: (app: string) => `${app} off`,
  tap_nothing: "Pressed, nothing changed",
  // money
  nobody_owes: "Nobody owes cash.",
  received: "Received",
  cash_sheet_title: (name: string) => `Cash from ${name}`,
  amount: "Amount (₹)",
  receipt_no: "Receipt or slip number",
  note: "Note",
  cash_note_default: "Cash handed in at hub",
  record_cash: "Record cash",
  cash_done: (amt: string, name: string) => `${amt} recorded from ${name}.`,
  cash_bad_amount: "Enter an amount above zero.",
  cash_bad_ref: "Enter the receipt number (3 letters or more).",
  cash_dup: "That receipt number was already used for this driver.",
  cash_fail: "Could not record the cash. Try again.",
  withdrawal_requests: "Withdrawal requests",
  no_withdrawals: "No withdrawal requests waiting.",
  pay_now: "Pay now",
  mark_paid: "Mark paid",
  reject: "Reject",
  approve: "Approve",
  payable_now: (amt: string) => `Can be paid now: ${amt}`,
  less_than_asked: "Less than asked: cannot be paid yet.",
  pay_to: (what: string) => `Pay to ${what}`,
  no_bank: "No bank or UPI saved",
  paid_ref: "How was it paid? (UTR, slip, cash)",
  reject_why: "Why? The driver sees this.",
  pay_done: "Marked as paid.",
  pay_sent: "Payment sent.",
  reject_done: "Rejected.",
  action_fail: "That did not go through. Try again.",
  ref_needed: "Enter how it was paid.",
  // inbox
  all: "All",
  inbox_empty: "Nothing waiting.",
  new_count: (n: number) => `${n} new`,
  reply: "Reply",
  mark_read: "Mark read",
  req: { advance: "Advance", holiday: "Leave", extra_hours: "Extra hours" } as Record<string, string>,
  approved: "Approved.",
  // cars and shift change
  tab_cars: "Cars",
  cars_none: "No cars in this hub.",
  day_short: "Day",
  night_short: "Night",
  battery: "Battery",
  odometer: "Odometer",
  last_change: (when: string) => `Last shift change ${when}`,
  never_changed: "No shift change recorded yet",
  damage_tag: "Damage noted",
  shift_change: "Shift change",
  returning: "Returning the car",
  taking: "Taking the car",
  nobody: "Nobody",
  battery_pct: "Battery (%)",
  odometer_km: "Odometer (km)",
  car_photos: "Photos of the car",
  photo_labels: { front: "Front", back: "Back", left: "Left side", right: "Right side", dashboard: "Dashboard", damage: "Damage" } as Record<string, string>,
  photos_count: (n: number, of: number) => `${n} of ${of} photos taken`,
  new_damage: "New damage (leave blank if none)",
  damage_placeholder: "Scratch on the rear bumper",
  damage_photo: "Photo of the damage",
  cash_due_from: (name: string) => `Cash due from ${name}`,
  confirm_handover: "Confirm shift change",
  handover_done: (car: string) => `Shift change recorded for ${car}.`,
  ho_err: {
    driver_required: "Choose who is returning or taking the car.",
    same_driver: "The same driver cannot return and take the car.",
    odometer_lower: "The odometer is lower than last time. Check the number.",
    photo_too_large: "A photo is too large. Take it again.",
    too_many_photos: "Too many photos.",
  } as Record<string, string>,
  ho_bad_battery: "Battery must be between 0 and 100.",
  camera_denied: "Allow the camera in the phone's settings to take photos.",
  // earnings
  enter_earnings: "Enter earnings",
  earnings_progress: (n: number, of: number) => `${n} of ${of} drivers entered`,
  earnings_title: "Daily earnings",
  not_entered: "Not entered",
  fares_total: "Total fares (₹)",
  cash_collected: "Cash collected (₹)",
  from_report: "From the Uber report. It cannot be changed here.",
  earn_saved: (name: string) => `Saved for ${name}.`,
  earn_bad: "Enter amounts of zero or more.",
  earn_cash_more: "Cash cannot be more than the total fares.",
  earn_nothing: "Enter the total fares for at least one app.",
  today_word: "Today",
  yesterday_word: "Yesterday",
  reasons: REASONS_EN,
};

type HubText = typeof en;

const hi: HubText = {
  app_name: "Ride91 Hub",
  signin_title: "साइन इन",
  signin_sub: "अपना हब मैनेजर लॉगिन इस्तेमाल करें",
  username: "यूज़रनेम",
  password: "पासवर्ड",
  signin: "साइन इन",
  signin_bad: "यूज़रनेम या पासवर्ड गलत है।",
  signin_locked: "बहुत बार कोशिश हुई। 15 मिनट बाद फिर कोशिश करें।",
  signin_fail: "साइन इन नहीं हो सका। नेटवर्क जाँचें।",
  pick_hub: "कौन-सा हब?",
  pick_hub_sub: "आपका खाता सभी हब देख सकता है। एक चुनें।",
  sign_out: "साइन आउट",
  change_hub: "हब बदलें",
  tab_today: "आज",
  tab_drivers: "ड्राइवर",
  tab_money: "पैसा",
  tab_inbox: "इनबॉक्स",
  call: "कॉल",
  message: "संदेश",
  cancel: "रद्द",
  save: "सेव",
  loading: "लोड हो रहा है…",
  offline: "कनेक्शन नहीं है। पिछली जानकारी दिख रही है।",
  none: "—",
  on_duty_now: "अभी ड्यूटी पर",
  coming: "आ रहे हैं",
  not_coming: "नहीं आ रहे",
  no_answer: "जवाब नहीं",
  needs_you: "अभी ध्यान दें",
  all_clear: "अभी कुछ भी बाकी नहीं है।",
  cash_to_collect: "लेने वाला नकद",
  withdrawals: "निकासी",
  requests: "अनुरोध",
  messages: "संदेश",
  no_shift_times: (n) => `${n} ड्राइवर का शिफ़्ट समय तय नहीं है, इसलिए उनका अलार्म नहीं बजेगा। ड्राइवर के पेज पर समय डालें।`,
  att: {
    not_coming: "नहीं आ रहे",
    not_started: "ड्यूटी शुरू नहीं की",
    no_answer: "अलार्म का जवाब नहीं दिया",
    late: "आने को कहा, पर शुरू नहीं किया",
    tracking_stopped: "ट्रैकिंग बंद है",
    over_cash_limit: "नकद सीमा से ज़्यादा",
  },
  att_location_off: "फ़ोन में लोकेशन बंद है",
  att_no_signal: "10 मिनट से लोकेशन नहीं मिली",
  back_by: (d) => `${d} तक वापस`,
  shift_at: (t) => `शिफ़्ट ${t}`,
  search: "नाम या फ़ोन खोजें",
  no_drivers: "इस हब में कोई ड्राइवर नहीं है।",
  status: {
    no_shift_time: "शिफ़्ट समय नहीं", alarm_pending: "अलार्म बाकी", ringing: "अलार्म बज रहा है", no_answer: "जवाब नहीं",
    coming: "आ रहे हैं", not_coming: "नहीं आ रहे", late: "देर", not_started: "शुरू नहीं", started: "ड्यूटी पर",
  },
  on_duty: "ड्यूटी पर",
  off_duty: "ड्यूटी पर नहीं",
  not_online: "किसी ऐप पर ऑनलाइन नहीं",
  charging: "चार्जिंग",
  to_charger: "चार्जर की ओर",
  on_duty_for: (d) => `ड्यूटी पर ${d}`,
  owes: (amt) => `${amt} बाकी`,
  over_limit: "सीमा से ज़्यादा",
  shift_time: "शिफ़्ट का समय",
  shift_time_hint: "24 घंटे वाला समय, जैसे 07:00। अलार्म एक घंटा पहले बजता है।",
  shift_saved: "शिफ़्ट का समय सेव हो गया।",
  shift_bad: "समय HH:MM में लिखें, जैसे 07:00।",
  car: "गाड़ी",
  no_car: "कोई गाड़ी नहीं दी गई",
  cash_owed: "बाकी नकद",
  cash_received: "नकद मिला",
  working: "काम का समय",
  recent_taps: "आज की गतिविधि",
  no_taps: "आज अभी कोई बटन नहीं दबाया गया।",
  open_map: "नक्शा",
  conversation: "संदेश",
  no_messages: "अभी कोई संदेश नहीं।",
  type_message: "संदेश लिखें…",
  send: "भेजें",
  automatic: "अपने-आप",
  taps: {
    start_duty: "ड्यूटी शुरू की", end_duty: "ड्यूटी खत्म की", to_charger: "चार्जर की ओर",
    charging_started: "चार्जिंग शुरू", charging_finished: "चार्जिंग पूरी",
  },
  tap_on: (app) => `${app} चालू`,
  tap_off: (app) => `${app} बंद`,
  tap_nothing: "दबाया, कुछ नहीं बदला",
  nobody_owes: "किसी पर नकद बाकी नहीं है।",
  received: "मिल गया",
  cash_sheet_title: (name) => `${name} से नकद`,
  amount: "राशि (₹)",
  receipt_no: "रसीद या स्लिप नंबर",
  note: "नोट",
  cash_note_default: "हब पर नकद जमा किया",
  record_cash: "नकद दर्ज करें",
  cash_done: (amt, name) => `${name} से ${amt} दर्ज हुए।`,
  cash_bad_amount: "शून्य से ज़्यादा राशि लिखें।",
  cash_bad_ref: "रसीद नंबर लिखें (कम से कम 3 अक्षर)।",
  cash_dup: "यह रसीद नंबर इस ड्राइवर के लिए पहले इस्तेमाल हो चुका है।",
  cash_fail: "नकद दर्ज नहीं हो सका। फिर कोशिश करें।",
  withdrawal_requests: "निकासी के अनुरोध",
  no_withdrawals: "कोई निकासी अनुरोध बाकी नहीं है।",
  pay_now: "अभी भुगतान करें",
  mark_paid: "भुगतान हुआ",
  reject: "अस्वीकार",
  approve: "मंज़ूर",
  payable_now: (amt) => `अभी दिया जा सकता है: ${amt}`,
  less_than_asked: "माँगी गई राशि से कम है: अभी नहीं दिया जा सकता।",
  pay_to: (what) => `${what} में भुगतान`,
  no_bank: "बैंक या UPI सेव नहीं है",
  paid_ref: "भुगतान कैसे किया? (UTR, स्लिप, नकद)",
  reject_why: "क्यों? ड्राइवर को यह दिखेगा।",
  pay_done: "भुगतान दर्ज हुआ।",
  pay_sent: "भुगतान भेज दिया गया।",
  reject_done: "अस्वीकार किया गया।",
  action_fail: "यह नहीं हो सका। फिर कोशिश करें।",
  ref_needed: "लिखें कि भुगतान कैसे किया।",
  all: "सभी",
  inbox_empty: "कुछ भी बाकी नहीं है।",
  new_count: (n) => `${n} नए`,
  reply: "जवाब दें",
  mark_read: "पढ़ा हुआ",
  req: { advance: "एडवांस", holiday: "छुट्टी", extra_hours: "अतिरिक्त घंटे" },
  approved: "मंज़ूर किया गया।",
  // cars and shift change
  tab_cars: "गाड़ियाँ",
  cars_none: "इस हब में कोई गाड़ी नहीं है।",
  day_short: "दिन",
  night_short: "रात",
  battery: "बैटरी",
  odometer: "ओडोमीटर",
  last_change: (when) => `पिछला शिफ़्ट बदलाव ${when}`,
  never_changed: "अभी तक कोई शिफ़्ट बदलाव दर्ज नहीं",
  damage_tag: "नुकसान दर्ज",
  shift_change: "शिफ़्ट बदलाव",
  returning: "गाड़ी लौटा रहे हैं",
  taking: "गाड़ी ले जा रहे हैं",
  nobody: "कोई नहीं",
  battery_pct: "बैटरी (%)",
  odometer_km: "ओडोमीटर (किमी)",
  car_photos: "गाड़ी की फ़ोटो",
  photo_labels: { front: "आगे", back: "पीछे", left: "बायाँ हिस्सा", right: "दायाँ हिस्सा", dashboard: "डैशबोर्ड", damage: "नुकसान" },
  photos_count: (n, of) => `${of} में से ${n} फ़ोटो ली गईं`,
  new_damage: "नया नुकसान (न हो तो खाली छोड़ें)",
  damage_placeholder: "पीछे के बम्पर पर खरोंच",
  damage_photo: "नुकसान की फ़ोटो",
  cash_due_from: (name) => `${name} से लेने वाला नकद`,
  confirm_handover: "शिफ़्ट बदलाव पक्का करें",
  handover_done: (car) => `${car} का शिफ़्ट बदलाव दर्ज हुआ।`,
  ho_err: {
    driver_required: "चुनें कि गाड़ी कौन लौटा रहा है या ले जा रहा है।",
    same_driver: "एक ही ड्राइवर गाड़ी लौटा और ले नहीं सकता।",
    odometer_lower: "ओडोमीटर पिछली बार से कम है। नंबर जाँचें।",
    photo_too_large: "एक फ़ोटो बहुत बड़ी है। दोबारा लें।",
    too_many_photos: "बहुत ज़्यादा फ़ोटो हैं।",
  },
  ho_bad_battery: "बैटरी 0 से 100 के बीच होनी चाहिए।",
  camera_denied: "फ़ोटो लेने के लिए फ़ोन की सेटिंग में कैमरे की अनुमति दें।",
  // earnings
  enter_earnings: "कमाई दर्ज करें",
  earnings_progress: (n, of) => `${of} में से ${n} ड्राइवर दर्ज`,
  earnings_title: "रोज़ की कमाई",
  not_entered: "दर्ज नहीं",
  fares_total: "कुल किराया (₹)",
  cash_collected: "लिया गया नकद (₹)",
  from_report: "यह Uber रिपोर्ट से है। यहाँ बदला नहीं जा सकता।",
  earn_saved: (name) => `${name} के लिए सेव हुआ।`,
  earn_bad: "शून्य या उससे ज़्यादा राशि लिखें।",
  earn_cash_more: "नकद कुल किराये से ज़्यादा नहीं हो सकता।",
  earn_nothing: "कम से कम एक ऐप का कुल किराया लिखें।",
  today_word: "आज",
  yesterday_word: "कल",
  reasons: REASONS_HI,
};

export const useHubText = (): HubText => {
  const { lang } = useI18n();
  return lang === "hi" ? hi : en;
};

export type { HubText };
