// Everything the hub manager app says, in English and Hindi. The language is
// the one chosen with the EN / हिं switch (shared with the driver app's setting;
// Kannada falls back to English here).

import { useI18n } from "@/src/i18n";

const REASONS_EN: Record<string, string> = {
  unwell: "Unwell", family_emergency: "Family emergency", vehicle_problem: "Vehicle problem",
  transport_problem: "Transport problem", personal: "Personal", other: "Other",
};
const REASONS_HI: Record<string, string> = {
  unwell: "तबीयत खराब", family_emergency: "पारिवारिक आपात स्थिति", vehicle_problem: "गाड़ी में समस्या",
  transport_problem: "आने-जाने में समस्या", personal: "निजी कारण", other: "अन्य",
};

const en = {
  // sign in
  app_name: "Ride91 Hub",
  signin_title: "Sign in",
  signin_sub: "Use your hub manager login",
  username: "Username",
  password: "Password",
  signin: "Sign in",
  signin_bad: "Wrong username or password.",
  signin_locked: "Too many tries. Wait 15 minutes and try again.",
  signin_fail: "Could not sign in. Check your network.",
  pick_hub: "Which hub?",
  pick_hub_sub: "Your account covers every hub. Choose one to open.",
  sign_out: "Sign out",
  change_hub: "Change hub",
  // tabs
  tab_today: "Today",
  tab_drivers: "Drivers",
  tab_money: "Money",
  tab_inbox: "Inbox",
  // general
  call: "Call",
  message: "Message",
  cancel: "Cancel",
  save: "Save",
  loading: "Loading…",
  offline: "No connection. Showing the last update.",
  none: "—",
  // today
  on_duty_now: "On duty now",
  coming: "Coming",
  not_coming: "Not coming",
  no_answer: "No answer",
  needs_you: "Needs you now",
  all_clear: "Nothing needs you right now.",
  of_on_duty: (total: number) => `of ${total} on duty`,
  updated_at: (time: string) => `Updated ${time}`,
  next_shift: (time: string, n: number) => `Next shift ${time} · ${n} ${n === 1 ? "driver" : "drivers"}`,
  quick_title: "Do now",
  qa_shift_sub: "Hand a car from one driver to the next",
  qa_cash_sub: (amt: string) => `${amt} to collect`,
  qa_earn_sub: "Each driver's fares for the day",
  qa_map_sub: "See where the drivers are",
  waiting_title: "Waiting for you",
  all_drivers: "All drivers",
  nobody_on_duty: "Nobody is on duty right now.",
  cash_to_collect: "Cash to collect",
  withdrawals: "Withdrawals",
  requests: "Requests",
  messages: "Messages",
  no_shift_times: (n: number) => `${n} driver${n === 1 ? " has" : "s have"} no shift time, so no alarm rings for them. Set it on the driver's page.`,
  att: {
    not_coming: "Not coming",
    not_started: "Has not started duty",
    no_answer: "Did not answer the alarm",
    late: "Said coming, not started",
    tracking_stopped: "Tracking stopped",
    over_cash_limit: "Cash over the limit",
  } as Record<string, string>,
  att_location_off: "Location is off on the phone",
  att_no_signal: "No position for over 10 minutes",
  back_by: (d: string) => `back by ${d}`,
  shift_at: (t: string) => `shift ${t}`,
  // drivers
  search: "Search name or phone",
  no_drivers: "No drivers in this hub.",
  status: {
    no_shift_time: "No shift time", alarm_pending: "Alarm not rung", ringing: "Alarm ringing", no_answer: "No answer",
    coming: "Coming", not_coming: "Not coming", late: "Late", not_started: "Not started", started: "On duty",
  } as Record<string, string>,
  on_duty: "On duty",
  off_duty: "Off duty",
  not_online: "Not online on any app",
  add_driver: "+ Add driver",
  edit: "Edit",
  df_add_title: "Add a driver",
  df_edit_title: "Edit driver",
  df_name: "Name",
  df_phone: "Phone number",
  df_phone_hint: "The driver signs in to the driver app with this number.",
  df_password: "App password",
  df_new_password: "New app password",
  df_password_keep: "Leave empty to keep the current one",
  df_password_hint: "At least 6 characters. Tell it to the driver; they sign in with it.",
  df_shift: "Shift",
  df_car: "Car",
  df_no_car: "No car yet",
  df_slot_free: (shift: string) => `${shift} slot is free`,
  df_slot_with: (name: string) => `Already with ${name}`,
  df_add: "Add driver",
  df_need_name: "Enter the driver's name.",
  df_bad_phone: "Enter a 10-digit mobile number.",
  df_bad_password: "The password needs at least 6 characters.",
  df_bad_time: "Enter the shift time like 07:00 or 19:30.",
  df_phone_taken: "That phone number is already registered to a driver. If they were removed earlier, bring them back from Hub settings.",
  df_slot_taken: "That car already has a driver for this shift.",
  df_remove: "Remove driver",
  df_remove_sure: (name: string) => `Remove ${name}? They will not be able to sign in and their car is freed. Their cash and salary records are kept.`,
  df_remove_owes: (amt: string) => `They still owe ${amt}.`,
  df_remove_yes: "Yes, remove",
  // cars: the car's page, inspections and service history
  car_add: "+ Add car",
  car_add_title: "Add a car",
  car_number: "Number plate",
  car_model: "Model",
  car_number_bad: "Enter the number plate.",
  car_number_taken: "A car with that number already exists.",
  car_hub_full: "This hub is full. Ask the office to raise its capacity.",
  car_remove: "Remove car",
  car_remove_sure: (num: string) => `Remove ${num} from the hub? Its history is kept.`,
  car_in_use: "A driver still has this car. Take them off it first (Drivers, then Edit).",
  car_remove_yes: "Yes, remove",
  car_limited: "Inspections and service history are not switched on at the office yet. Shift change works as before.",
  car_inspect: "Inspect car",
  car_add_service: "Add service",
  car_last_done: "Last done",
  car_never: "Not recorded",
  car_inspections: "Inspections",
  car_no_inspections: "No inspection recorded yet.",
  car_last_inspected: (when: string) => `Inspected ${when}`,
  car_never_inspected: "Never inspected",
  car_service_history: "Service history",
  car_no_services: "No service recorded yet.",
  car_shift_changes: "Shift changes",
  tap_for_photos: (n: number) => `${n} ${n === 1 ? "photo" : "photos"} · tap to see`,
  photos_none: "No photos were taken.",
  by_who: (name: string) => `by ${name}`,
  check_items: {
    tyres: "Tyres", spare_tyre: "Spare tyre (stepney)", brake_fluid: "Brake fluid", coolant: "Coolant",
    motor_oil: "Motor oil", wipers: "Wipers", headlights: "Headlights", dash_camera: "Dash camera", gps: "GPS",
  } as Record<string, string>,
  service_kinds: {
    service: "Full service", tyres: "Tyres changed", wipers: "Wipers changed", brakes: "Brakes",
    battery: "Battery work", other: "Other work",
  } as Record<string, string>,
  check_ok: "OK",
  check_attention: "Needs attention",
  check_all_ok: "All OK",
  check_n_attention: (n: number) => `${n} ${n === 1 ? "needs" : "need"} attention`,
  check_mark_all_ok: "Mark all OK",
  check_note_ph: "What is wrong?",
  check_battery: "Battery performance report",
  check_battery_ph: "Health %, range on a full charge, charging problems…",
  check_notes: "Notes",
  check_notes_ph: "Anything else about this car",
  check_save: "Save inspection",
  check_saved: "Inspection saved.",
  check_nothing: "Mark at least one point, or write a note.",
  svc_kind: "What was done",
  svc_date: "Date done (YYYY-MM-DD)",
  svc_note: "Details",
  svc_cost: "Cost (₹), optional",
  svc_bad_date: "Enter the date like 2026-10-09, not in the future.",
  svc_note_needed: "Write what was done.",
  svc_saved: "Service saved.",
  car_added: "Car added.",
  // hub settings
  settings_title: "Hub settings",
  set_shift_all: "Shift time for everyone",
  set_shift_all_hint: "Sets the time for every day or night driver at once. Each driver's alarm follows.",
  set_day: "Day drivers",
  set_night: "Night drivers",
  set_everyone: "Everyone",
  set_done: (n: number) => `Shift time set for ${n} ${n === 1 ? "driver" : "drivers"}.`,
  removed_title: "Removed drivers",
  removed_none: "No removed drivers.",
  restore: "Bring back",
  restored: (name: string) => `${name} is back in the hub. Give them a car from their page.`,
  pw_title: "Change my password",
  pw_old: "Current password",
  pw_new: "New password (10 or more characters)",
  pw_change: "Change password",
  pw_wrong: "The current password is wrong.",
  pw_short: "The new password needs at least 10 characters.",
  pw_done: "Password changed.",
  account: "Account",
  // a driver who phoned in
  phoned_in: "Driver phoned in?",
  mark_coming: "Mark coming",
  mark_not_coming: "Mark not coming",
  answer_why: "Why are they not coming?",
  back_by_label: "Back by (YYYY-MM-DD), optional",
  other_reason: "Reason",
  answer_saved: "Recorded.",
  answered_by_hub: (name: string) => `recorded by ${name}`,
  bad_date: "Enter the date like 2026-10-12.",
  need_reason: "Choose a reason.",
  // cash received
  cash_received_title: "Cash received",
  cash_received_none: "No cash recorded yet.",
  undo: "Undo",
  undone: "Undone",
  undo_sure: (amt: string, name: string) => `Undo ${amt} received from ${name}? They will owe it again.`,
  undo_yes: "Yes, undo",
  undo_done: "Entry undone.",
  undo_old: "Too old to undo here. Ask the office.",
  // message everyone
  msg_all: "Message all",
  msg_all_title: "Message all drivers",
  msg_all_sent: (n: number) => `Sent to ${n} ${n === 1 ? "driver" : "drivers"}.`,
  view_list: "List",
  view_map: "Map",
  map_count: (n: number, total: number) => `${n} of ${total} drivers on the map`,
  map_none: "No driver has sent a position yet. A driver appears here once they start duty.",
  map_open: "Open",
  map_fit: "Show all",
  map_live: "On duty",
  map_quiet: "On duty, no position for 10+ min",
  map_off: "Off duty, last seen",
  seen_now: "Seen just now",
  seen_min: (n: number) => `Seen ${n} min ago`,
  seen_hr: (n: number) => `Seen ${n} h ago`,
  seen_day: (n: number) => `Seen ${n} ${n === 1 ? "day" : "days"} ago`,
  charging: "Charging",
  to_charger: "Going to charger",
  on_duty_for: (d: string) => `On duty ${d}`,
  owes: (amt: string) => `Owes ${amt}`,
  over_limit: "over limit",
  // driver page
  shift_time: "Shift time",
  shift_time_hint: "24-hour time, like 07:00. The alarm rings one hour before.",
  shift_saved: "Shift time saved.",
  shift_bad: "Enter the time as HH:MM, like 07:00.",
  car: "Car",
  no_car: "No car assigned",
  cash_owed: "Cash owed",
  cash_received: "Cash received",
  working: "Working",
  recent_taps: "Today's activity",
  no_taps: "No button presses yet today.",
  open_map: "Map",
  conversation: "Messages",
  no_messages: "No messages yet.",
  type_message: "Write a message…",
  send: "Send",
  automatic: "automatic",
  taps: {
    start_duty: "Started duty", end_duty: "Ended duty", to_charger: "Going to charger",
    charging_started: "Charging started", charging_finished: "Charging finished",
  } as Record<string, string>,
  tap_on: (app: string) => `${app} on`,
  tap_off: (app: string) => `${app} off`,
  tap_nothing: "Pressed, nothing changed",
  // money
  nobody_owes: "Nobody owes cash.",
  received: "Received",
  cash_sheet_title: (name: string) => `Cash from ${name}`,
  amount: "Amount (₹)",
  receipt_no: "Receipt or slip number",
  note: "Note",
  cash_note_default: "Cash handed in at hub",
  record_cash: "Record cash",
  cash_done: (amt: string, name: string) => `${amt} recorded from ${name}.`,
  cash_bad_amount: "Enter an amount above zero.",
  cash_bad_ref: "Enter the receipt number (3 letters or more).",
  cash_dup: "That receipt number was already used for this driver.",
  cash_fail: "Could not record the cash. Try again.",
  withdrawal_requests: "Withdrawal requests",
  no_withdrawals: "No withdrawal requests waiting.",
  pay_now: "Pay now",
  mark_paid: "Mark paid",
  reject: "Reject",
  approve: "Approve",
  payable_now: (amt: string) => `Can be paid now: ${amt}`,
  less_than_asked: "Less than asked: cannot be paid yet.",
  pay_to: (what: string) => `Pay to ${what}`,
  no_bank: "No bank or UPI saved",
  paid_ref: "How was it paid? (UTR, slip, cash)",
  reject_why: "Why? The driver sees this.",
  pay_done: "Marked as paid.",
  pay_sent: "Payment sent.",
  reject_done: "Rejected.",
  action_fail: "That did not go through. Try again.",
  ref_needed: "Enter how it was paid.",
  // inbox
  all: "All",
  inbox_empty: "Nothing waiting.",
  new_count: (n: number) => `${n} new`,
  reply: "Reply",
  mark_read: "Mark read",
  req: { advance: "Advance", holiday: "Leave", extra_hours: "Extra hours" } as Record<string, string>,
  approved: "Approved.",
  // cars and shift change
  tab_cars: "Cars",
  cars_none: "No cars in this hub.",
  day_short: "Day",
  night_short: "Night",
  battery: "Battery",
  odometer: "Odometer",
  last_change: (when: string) => `Last shift change ${when}`,
  never_changed: "No shift change recorded yet",
  damage_tag: "Damage noted",
  shift_change: "Shift change",
  returning: "Returning the car",
  taking: "Taking the car",
  nobody: "Nobody",
  battery_pct: "Battery (%)",
  odometer_km: "Odometer (km)",
  car_photos: "Photos of the car",
  photo_labels: { front: "Front", back: "Back", left: "Left side", right: "Right side", dashboard: "Dashboard", damage: "Damage" } as Record<string, string>,
  photos_count: (n: number, of: number) => `${n} of ${of} photos taken`,
  new_damage: "New damage (leave blank if none)",
  damage_placeholder: "Scratch on the rear bumper",
  damage_photo: "Photo of the damage",
  cash_due_from: (name: string) => `Cash due from ${name}`,
  confirm_handover: "Confirm shift change",
  handover_done: (car: string) => `Shift change recorded for ${car}.`,
  ho_err: {
    driver_required: "Choose who is returning or taking the car.",
    same_driver: "The same driver cannot return and take the car.",
    odometer_lower: "The odometer is lower than last time. Check the number.",
    photo_too_large: "A photo is too large. Take it again.",
    too_many_photos: "Too many photos.",
  } as Record<string, string>,
  ho_bad_battery: "Battery must be between 0 and 100.",
  camera_denied: "Allow the camera in the phone's settings to take photos.",
  // earnings
  enter_earnings: "Enter earnings",
  earnings_progress: (n: number, of: number) => `${n} of ${of} drivers entered`,
  earnings_title: "Daily earnings",
  not_entered: "Not entered",
  fares_total: "Total fares (₹)",
  cash_collected: "Cash collected (₹)",
  from_report: "From the Uber report. It cannot be changed here.",
  earn_saved: (name: string) => `Saved for ${name}.`,
  earn_bad: "Enter amounts of zero or more.",
  earn_cash_more: "Cash cannot be more than the total fares.",
  earn_nothing: "Enter the total fares for at least one app.",
  today_word: "Today",
  yesterday_word: "Yesterday",
  reasons: REASONS_EN,
};

type HubText = typeof en;

const hi: HubText = {
  app_name: "Ride91 Hub",
  signin_title: "साइन इन",
  signin_sub: "अपना हब मैनेजर लॉगिन इस्तेमाल करें",
  username: "यूज़रनेम",
  password: "पासवर्ड",
  signin: "साइन इन",
  signin_bad: "यूज़रनेम या पासवर्ड गलत है।",
  signin_locked: "बहुत बार कोशिश हुई। 15 मिनट बाद फिर कोशिश करें।",
  signin_fail: "साइन इन नहीं हो सका। नेटवर्क जाँचें।",
  pick_hub: "कौन-सा हब?",
  pick_hub_sub: "आपका खाता सभी हब देख सकता है। एक चुनें।",
  sign_out: "साइन आउट",
  change_hub: "हब बदलें",
  tab_today: "आज",
  tab_drivers: "ड्राइवर",
  tab_money: "पैसा",
  tab_inbox: "इनबॉक्स",
  call: "कॉल",
  message: "संदेश",
  cancel: "रद्द",
  save: "सेव",
  loading: "लोड हो रहा है…",
  offline: "कनेक्शन नहीं है। पिछली जानकारी दिख रही है।",
  none: "—",
  on_duty_now: "अभी ड्यूटी पर",
  coming: "आ रहे हैं",
  not_coming: "नहीं आ रहे",
  no_answer: "जवाब नहीं",
  needs_you: "अभी ध्यान दें",
  all_clear: "अभी कुछ भी बाकी नहीं है।",
  of_on_duty: (total: number) => `/ ${total} ड्यूटी पर`,
  updated_at: (time: string) => `${time} पर अपडेट`,
  next_shift: (time: string, n: number) => `अगली शिफ़्ट ${time} · ${n} ड्राइवर`,
  quick_title: "अभी करें",
  qa_shift_sub: "गाड़ी एक ड्राइवर से दूसरे को सौंपें",
  qa_cash_sub: (amt: string) => `${amt} लेना है`,
  qa_earn_sub: "हर ड्राइवर की दिन की कमाई",
  qa_map_sub: "देखें ड्राइवर कहाँ हैं",
  waiting_title: "आपका इंतज़ार",
  all_drivers: "सभी ड्राइवर",
  nobody_on_duty: "अभी कोई ड्यूटी पर नहीं है।",
  cash_to_collect: "लेने वाला नकद",
  withdrawals: "निकासी",
  requests: "अनुरोध",
  messages: "संदेश",
  no_shift_times: (n) => `${n} ड्राइवर का शिफ़्ट समय तय नहीं है, इसलिए उनका अलार्म नहीं बजेगा। ड्राइवर के पेज पर समय डालें।`,
  att: {
    not_coming: "नहीं आ रहे",
    not_started: "ड्यूटी शुरू नहीं की",
    no_answer: "अलार्म का जवाब नहीं दिया",
    late: "आने को कहा, पर शुरू नहीं किया",
    tracking_stopped: "ट्रैकिंग बंद है",
    over_cash_limit: "नकद सीमा से ज़्यादा",
  },
  att_location_off: "फ़ोन में लोकेशन बंद है",
  att_no_signal: "10 मिनट से लोकेशन नहीं मिली",
  back_by: (d) => `${d} तक वापस`,
  shift_at: (t) => `शिफ़्ट ${t}`,
  search: "नाम या फ़ोन खोजें",
  no_drivers: "इस हब में कोई ड्राइवर नहीं है।",
  status: {
    no_shift_time: "शिफ़्ट समय नहीं", alarm_pending: "अलार्म बाकी", ringing: "अलार्म बज रहा है", no_answer: "जवाब नहीं",
    coming: "आ रहे हैं", not_coming: "नहीं आ रहे", late: "देर", not_started: "शुरू नहीं", started: "ड्यूटी पर",
  },
  on_duty: "ड्यूटी पर",
  off_duty: "ड्यूटी पर नहीं",
  not_online: "किसी ऐप पर ऑनलाइन नहीं",
  add_driver: "+ ड्राइवर जोड़ें",
  edit: "बदलें",
  df_add_title: "ड्राइवर जोड़ें",
  df_edit_title: "ड्राइवर बदलें",
  df_name: "नाम",
  df_phone: "फ़ोन नंबर",
  df_phone_hint: "ड्राइवर इसी नंबर से ड्राइवर ऐप में साइन इन करता है।",
  df_password: "ऐप पासवर्ड",
  df_new_password: "नया ऐप पासवर्ड",
  df_password_keep: "पुराना रखने के लिए खाली छोड़ें",
  df_password_hint: "कम से कम 6 अक्षर। ड्राइवर को बता दें; वह इसी से साइन इन करेगा।",
  df_shift: "शिफ़्ट",
  df_car: "गाड़ी",
  df_no_car: "अभी कोई गाड़ी नहीं",
  df_slot_free: (shift: string) => `${shift} की जगह खाली है`,
  df_slot_with: (name: string) => `पहले से ${name} के पास`,
  df_add: "ड्राइवर जोड़ें",
  df_need_name: "ड्राइवर का नाम लिखें।",
  df_bad_phone: "10 अंकों का मोबाइल नंबर लिखें।",
  df_bad_password: "पासवर्ड में कम से कम 6 अक्षर चाहिए।",
  df_bad_time: "शिफ़्ट का समय 07:00 या 19:30 की तरह लिखें।",
  df_phone_taken: "यह फ़ोन नंबर पहले से किसी ड्राइवर के नाम है। अगर उसे पहले हटाया गया था, तो हब सेटिंग से वापस लाएँ।",
  df_slot_taken: "इस गाड़ी पर इस शिफ़्ट का ड्राइवर पहले से है।",
  df_remove: "ड्राइवर हटाएँ",
  df_remove_sure: (name: string) => `${name} को हटाएँ? वह साइन इन नहीं कर पाएगा और उसकी गाड़ी खाली हो जाएगी। नकद और वेतन का रिकॉर्ड बना रहेगा।`,
  df_remove_owes: (amt: string) => `उस पर अभी ${amt} बाकी है।`,
  df_remove_yes: "हाँ, हटाएँ",
  // cars: the car's page, inspections and service history
  car_add: "+ गाड़ी जोड़ें",
  car_add_title: "गाड़ी जोड़ें",
  car_number: "नंबर प्लेट",
  car_model: "मॉडल",
  car_number_bad: "नंबर प्लेट लिखें।",
  car_number_taken: "इस नंबर की गाड़ी पहले से है।",
  car_hub_full: "यह हब भर गया है। ऑफ़िस से इसकी क्षमता बढ़वाएँ।",
  car_remove: "गाड़ी हटाएँ",
  car_remove_sure: (num: string) => `${num} को हब से हटाएँ? इसका रिकॉर्ड बना रहेगा।`,
  car_in_use: "यह गाड़ी अभी किसी ड्राइवर के पास है। पहले उसे हटाएँ (ड्राइवर, फिर बदलें)।",
  car_remove_yes: "हाँ, हटाएँ",
  car_limited: "जाँच और सर्विस का इतिहास अभी ऑफ़िस की तरफ़ से चालू नहीं है। शिफ़्ट बदलाव पहले की तरह चलेगा।",
  car_inspect: "गाड़ी की जाँच",
  car_add_service: "सर्विस जोड़ें",
  car_last_done: "पिछली बार",
  car_never: "दर्ज नहीं",
  car_inspections: "जाँचें",
  car_no_inspections: "अभी कोई जाँच दर्ज नहीं है।",
  car_last_inspected: (when: string) => `जाँच ${when}`,
  car_never_inspected: "कभी जाँच नहीं हुई",
  car_service_history: "सर्विस का इतिहास",
  car_no_services: "अभी कोई सर्विस दर्ज नहीं है।",
  car_shift_changes: "शिफ़्ट बदलाव",
  tap_for_photos: (n: number) => `${n} फ़ोटो · देखने के लिए दबाएँ`,
  photos_none: "कोई फ़ोटो नहीं ली गई।",
  by_who: (name: string) => `${name} द्वारा`,
  check_items: {
    tyres: "टायर", spare_tyre: "स्टेपनी टायर", brake_fluid: "ब्रेक फ़्लुइड", coolant: "कूलेंट",
    motor_oil: "मोटर ऑयल", wipers: "वाइपर", headlights: "हेडलाइट", dash_camera: "डैश कैमरा", gps: "GPS",
  } as Record<string, string>,
  service_kinds: {
    service: "पूरी सर्विस", tyres: "टायर बदले", wipers: "वाइपर बदले", brakes: "ब्रेक",
    battery: "बैटरी का काम", other: "अन्य काम",
  } as Record<string, string>,
  check_ok: "ठीक",
  check_attention: "ध्यान दें",
  check_all_ok: "सब ठीक",
  check_n_attention: (n: number) => `${n} पर ध्यान दें`,
  check_mark_all_ok: "सब ठीक चुनें",
  check_note_ph: "क्या दिक्कत है?",
  check_battery: "बैटरी परफ़ॉर्मेंस रिपोर्ट",
  check_battery_ph: "हेल्थ %, फ़ुल चार्ज पर रेंज, चार्जिंग की दिक्कत…",
  check_notes: "नोट्स",
  check_notes_ph: "इस गाड़ी के बारे में और कुछ",
  check_save: "जाँच सेव करें",
  check_saved: "जाँच सेव हो गई।",
  check_nothing: "कम से कम एक चीज़ चुनें या नोट लिखें।",
  svc_kind: "क्या काम हुआ",
  svc_date: "काम की तारीख (YYYY-MM-DD)",
  svc_note: "विवरण",
  svc_cost: "खर्च (₹), ज़रूरी नहीं",
  svc_bad_date: "तारीख 2026-10-09 की तरह लिखें, आगे की नहीं।",
  svc_note_needed: "लिखें क्या काम हुआ।",
  svc_saved: "सर्विस सेव हो गई।",
  car_added: "गाड़ी जुड़ गई।",
  // hub settings
  settings_title: "हब सेटिंग",
  set_shift_all: "सबके लिए शिफ़्ट का समय",
  set_shift_all_hint: "दिन या रात के सभी ड्राइवरों का समय एक साथ तय होता है। हर ड्राइवर का अलार्म उसी के अनुसार बजेगा।",
  set_day: "दिन के ड्राइवर",
  set_night: "रात के ड्राइवर",
  set_everyone: "सभी",
  set_done: (n: number) => `${n} ड्राइवरों का शिफ़्ट समय तय हो गया।`,
  removed_title: "हटाए गए ड्राइवर",
  removed_none: "कोई हटाया गया ड्राइवर नहीं।",
  restore: "वापस लाएँ",
  restored: (name: string) => `${name} हब में वापस आ गया। उसके पेज से गाड़ी दें।`,
  pw_title: "मेरा पासवर्ड बदलें",
  pw_old: "मौजूदा पासवर्ड",
  pw_new: "नया पासवर्ड (10 या ज़्यादा अक्षर)",
  pw_change: "पासवर्ड बदलें",
  pw_wrong: "मौजूदा पासवर्ड गलत है।",
  pw_short: "नए पासवर्ड में कम से कम 10 अक्षर चाहिए।",
  pw_done: "पासवर्ड बदल गया।",
  account: "खाता",
  // a driver who phoned in
  phoned_in: "ड्राइवर ने फ़ोन किया?",
  mark_coming: "आ रहा है दर्ज करें",
  mark_not_coming: "नहीं आ रहा दर्ज करें",
  answer_why: "क्यों नहीं आ रहा?",
  back_by_label: "कब तक वापस (YYYY-MM-DD), ज़रूरी नहीं",
  other_reason: "कारण",
  answer_saved: "दर्ज हो गया।",
  answered_by_hub: (name: string) => `${name} ने दर्ज किया`,
  bad_date: "तारीख 2026-10-12 की तरह लिखें।",
  need_reason: "कारण चुनें।",
  // cash received
  cash_received_title: "मिला हुआ नकद",
  cash_received_none: "अभी कोई नकद दर्ज नहीं है।",
  undo: "वापस लें",
  undone: "वापस लिया गया",
  undo_sure: (amt: string, name: string) => `${name} से मिला ${amt} वापस लें? यह रकम फिर उस पर बाकी हो जाएगी।`,
  undo_yes: "हाँ, वापस लें",
  undo_done: "एंट्री वापस ली गई।",
  undo_old: "यह यहाँ से वापस नहीं हो सकती। ऑफ़िस से कहें।",
  // message everyone
  msg_all: "सबको संदेश",
  msg_all_title: "सभी ड्राइवरों को संदेश",
  msg_all_sent: (n: number) => `${n} ड्राइवरों को भेजा गया।`,
  view_list: "सूची",
  view_map: "नक्शा",
  map_count: (n: number, total: number) => `${total} में से ${n} ड्राइवर नक्शे पर`,
  map_none: "अभी तक किसी ड्राइवर की लोकेशन नहीं आई है। ड्यूटी शुरू करने पर ड्राइवर यहाँ दिखेगा।",
  map_open: "खोलें",
  map_fit: "सब दिखाएँ",
  map_live: "ड्यूटी पर",
  map_quiet: "ड्यूटी पर, 10+ मिनट से लोकेशन नहीं",
  map_off: "ड्यूटी पर नहीं, आख़िरी लोकेशन",
  seen_now: "अभी देखा गया",
  seen_min: (n: number) => `${n} मिनट पहले देखा गया`,
  seen_hr: (n: number) => `${n} घंटे पहले देखा गया`,
  seen_day: (n: number) => `${n} दिन पहले देखा गया`,
  charging: "चार्जिंग",
  to_charger: "चार्जर की ओर",
  on_duty_for: (d) => `ड्यूटी पर ${d}`,
  owes: (amt) => `${amt} बाकी`,
  over_limit: "सीमा से ज़्यादा",
  shift_time: "शिफ़्ट का समय",
  shift_time_hint: "24 घंटे वाला समय, जैसे 07:00। अलार्म एक घंटा पहले बजता है।",
  shift_saved: "शिफ़्ट का समय सेव हो गया।",
  shift_bad: "समय HH:MM में लिखें, जैसे 07:00।",
  car: "गाड़ी",
  no_car: "कोई गाड़ी नहीं दी गई",
  cash_owed: "बाकी नकद",
  cash_received: "नकद मिला",
  working: "काम का समय",
  recent_taps: "आज की गतिविधि",
  no_taps: "आज अभी कोई बटन नहीं दबाया गया।",
  open_map: "नक्शा",
  conversation: "संदेश",
  no_messages: "अभी कोई संदेश नहीं।",
  type_message: "संदेश लिखें…",
  send: "भेजें",
  automatic: "अपने-आप",
  taps: {
    start_duty: "ड्यूटी शुरू की", end_duty: "ड्यूटी खत्म की", to_charger: "चार्जर की ओर",
    charging_started: "चार्जिंग शुरू", charging_finished: "चार्जिंग पूरी",
  },
  tap_on: (app) => `${app} चालू`,
  tap_off: (app) => `${app} बंद`,
  tap_nothing: "दबाया, कुछ नहीं बदला",
  nobody_owes: "किसी पर नकद बाकी नहीं है।",
  received: "मिल गया",
  cash_sheet_title: (name) => `${name} से नकद`,
  amount: "राशि (₹)",
  receipt_no: "रसीद या स्लिप नंबर",
  note: "नोट",
  cash_note_default: "हब पर नकद जमा किया",
  record_cash: "नकद दर्ज करें",
  cash_done: (amt, name) => `${name} से ${amt} दर्ज हुए।`,
  cash_bad_amount: "शून्य से ज़्यादा राशि लिखें।",
  cash_bad_ref: "रसीद नंबर लिखें (कम से कम 3 अक्षर)।",
  cash_dup: "यह रसीद नंबर इस ड्राइवर के लिए पहले इस्तेमाल हो चुका है।",
  cash_fail: "नकद दर्ज नहीं हो सका। फिर कोशिश करें।",
  withdrawal_requests: "निकासी के अनुरोध",
  no_withdrawals: "कोई निकासी अनुरोध बाकी नहीं है।",
  pay_now: "अभी भुगतान करें",
  mark_paid: "भुगतान हुआ",
  reject: "अस्वीकार",
  approve: "मंज़ूर",
  payable_now: (amt) => `अभी दिया जा सकता है: ${amt}`,
  less_than_asked: "माँगी गई राशि से कम है: अभी नहीं दिया जा सकता।",
  pay_to: (what) => `${what} में भुगतान`,
  no_bank: "बैंक या UPI सेव नहीं है",
  paid_ref: "भुगतान कैसे किया? (UTR, स्लिप, नकद)",
  reject_why: "क्यों? ड्राइवर को यह दिखेगा।",
  pay_done: "भुगतान दर्ज हुआ।",
  pay_sent: "भुगतान भेज दिया गया।",
  reject_done: "अस्वीकार किया गया।",
  action_fail: "यह नहीं हो सका। फिर कोशिश करें।",
  ref_needed: "लिखें कि भुगतान कैसे किया।",
  all: "सभी",
  inbox_empty: "कुछ भी बाकी नहीं है।",
  new_count: (n) => `${n} नए`,
  reply: "जवाब दें",
  mark_read: "पढ़ा हुआ",
  req: { advance: "एडवांस", holiday: "छुट्टी", extra_hours: "अतिरिक्त घंटे" },
  approved: "मंज़ूर किया गया।",
  // cars and shift change
  tab_cars: "गाड़ियाँ",
  cars_none: "इस हब में कोई गाड़ी नहीं है।",
  day_short: "दिन",
  night_short: "रात",
  battery: "बैटरी",
  odometer: "ओडोमीटर",
  last_change: (when) => `पिछला शिफ़्ट बदलाव ${when}`,
  never_changed: "अभी तक कोई शिफ़्ट बदलाव दर्ज नहीं",
  damage_tag: "नुकसान दर्ज",
  shift_change: "शिफ़्ट बदलाव",
  returning: "गाड़ी लौटा रहे हैं",
  taking: "गाड़ी ले जा रहे हैं",
  nobody: "कोई नहीं",
  battery_pct: "बैटरी (%)",
  odometer_km: "ओडोमीटर (किमी)",
  car_photos: "गाड़ी की फ़ोटो",
  photo_labels: { front: "आगे", back: "पीछे", left: "बायाँ हिस्सा", right: "दायाँ हिस्सा", dashboard: "डैशबोर्ड", damage: "नुकसान" },
  photos_count: (n, of) => `${of} में से ${n} फ़ोटो ली गईं`,
  new_damage: "नया नुकसान (न हो तो खाली छोड़ें)",
  damage_placeholder: "पीछे के बम्पर पर खरोंच",
  damage_photo: "नुकसान की फ़ोटो",
  cash_due_from: (name) => `${name} से लेने वाला नकद`,
  confirm_handover: "शिफ़्ट बदलाव पक्का करें",
  handover_done: (car) => `${car} का शिफ़्ट बदलाव दर्ज हुआ।`,
  ho_err: {
    driver_required: "चुनें कि गाड़ी कौन लौटा रहा है या ले जा रहा है।",
    same_driver: "एक ही ड्राइवर गाड़ी लौटा और ले नहीं सकता।",
    odometer_lower: "ओडोमीटर पिछली बार से कम है। नंबर जाँचें।",
    photo_too_large: "एक फ़ोटो बहुत बड़ी है। दोबारा लें।",
    too_many_photos: "बहुत ज़्यादा फ़ोटो हैं।",
  },
  ho_bad_battery: "बैटरी 0 से 100 के बीच होनी चाहिए।",
  camera_denied: "फ़ोटो लेने के लिए फ़ोन की सेटिंग में कैमरे की अनुमति दें।",
  // earnings
  enter_earnings: "कमाई दर्ज करें",
  earnings_progress: (n, of) => `${of} में से ${n} ड्राइवर दर्ज`,
  earnings_title: "रोज़ की कमाई",
  not_entered: "दर्ज नहीं",
  fares_total: "कुल किराया (₹)",
  cash_collected: "लिया गया नकद (₹)",
  from_report: "यह Uber रिपोर्ट से है। यहाँ बदला नहीं जा सकता।",
  earn_saved: (name) => `${name} के लिए सेव हुआ।`,
  earn_bad: "शून्य या उससे ज़्यादा राशि लिखें।",
  earn_cash_more: "नकद कुल किराये से ज़्यादा नहीं हो सकता।",
  earn_nothing: "कम से कम एक ऐप का कुल किराया लिखें।",
  today_word: "आज",
  yesterday_word: "कल",
  reasons: REASONS_HI,
};

export const useHubText = (): HubText => {
  const { lang } = useI18n();
  return lang === "hi" ? hi : en;
};

export type { HubText };
